//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TobaccoNicotineApplication.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Country
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Country()
        {
            this.Currencies = new HashSet<Currency>();
            this.Values = new HashSet<Value>();
        }

        [Required(ErrorMessage = "Country Code is required.")]
        public short CountryCode { get; set; }

        [Required(ErrorMessage = "Continent Code is required.")]
        public short ContinentCode { get; set; }

        [Required(ErrorMessage = "Region Code is required.")]
        public short RegionCode { get; set; }

        [Required(ErrorMessage = "Country Name is required.")]
        [StringLength(70, MinimumLength = 4, ErrorMessage = "Country Name must be at least 4 characters.")]
        [RegularExpression("^[^0-9]+$", ErrorMessage = "Numbers aren't valid")]
        public string CountryName { get; set; }

        [Required(ErrorMessage = "Continent Name is required")]
        [StringLength(30, MinimumLength = 2, ErrorMessage = "Continent Name must be at least 2 characters.")]
        [RegularExpression("^[^0-9]+$", ErrorMessage = "Numbers aren't valid")]
        public string ContinentName { get; set; }

        [Required(ErrorMessage = "Region Name is required")]
        [StringLength(30, MinimumLength = 2, ErrorMessage = "Region Name must be at least 2 characters.")]
        [RegularExpression("^[^0-9]+$", ErrorMessage = "Numbers aren't valid")]
        public string RegionName { get; set; }

        [Required(ErrorMessage = "Pmi Coding is required.")]
        [StringLength(30, MinimumLength = 2, ErrorMessage = "Pmi Coding must be at least 2 characters.")]
        [RegularExpression("^[^0-9]+$", ErrorMessage = "Numbers aren't valid")]
        public string PmiCoding { get; set; }

        [Required(ErrorMessage = "Area Code is required.")]
        public bool AreaCode { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Currency> Currencies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Value> Values { get; set; }
    }
}
