//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TobaccoNicotineApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Currency
    {
        public short CountryCode { get; set; }
        public short Year { get; set; }
        public decimal Value { get; set; }
        public string Notes { get; set; }
    
        public virtual Country Countries { get; set; }
    }
}
