//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TobaccoNicotineApplication.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Value
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Value()
        {
            this.Sources = new HashSet<Source>();
        }

        [Required(ErrorMessage = "Country Code is required.")]
        public short CountryCode { get; set; }

        [Required(ErrorMessage = "Number is required.")]
        public short Number { get; set; }

        [Required(ErrorMessage = "Year is required.")]
        public short Year { get; set; }

        [Required(ErrorMessage = "Nomisma Code is required.")]
        public int NomismaCode { get; set; }

        [RegularExpression(@"[\d]{1,15}([.,][\d]{1,3})?", ErrorMessage = "Number must have a maximum of 3 decimals")]
        public Nullable<decimal> Data { get; set; }

        [RegularExpression(@"[\d]{1,15}([.,][\d]{1,3})?", ErrorMessage = "Number must have a maximum of 3 decimals")]
        public Nullable<decimal> DataPmi { get; set; }

        [StringLength(1000, MinimumLength = 0)]
        public string PublicNotes { get; set; }

        [StringLength(1000, MinimumLength = 0)]
        public string InternalNotes { get; set; }

        [StringLength(1000, MinimumLength = 0)]
        public string PmiNotes { get; set; }

        [RegularExpression(@"[\d]{1,15}([.,][\d]{1,3})?", ErrorMessage = "Number must have a maximum of 3 decimals")]
        public Nullable<decimal> DataUs { get; set; }
    
        public virtual Country Countries { get; set; }
        public virtual Variable Variables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Source> Sources { get; set; }
    }
}
